# NumPy

NumPy is a Linear Algebra library in Python and it is the holy grail and the main building block of Data Science using python, rely on NumPy as one of their main building blocks.

It is bound to several C Libraries which makes NumPy one of the fastest Libraries in Python.

We will learn the basics of NumPy, to get started we need to install it!

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.ndim

1

In [7]:
arr1.size

5

In [8]:
arr1.shape

(5,)

In [9]:
m = [[1,2,5,3],[5.9,4,5,3],[9,10,11,12]]
m

[[1, 2, 5, 3], [5.9, 4, 5, 3], [9, 10, 11, 12]]

In [10]:
b=np.array(m)
b

array([[ 1. ,  2. ,  5. ,  3. ],
       [ 5.9,  4. ,  5. ,  3. ],
       [ 9. , 10. , 11. , 12. ]])

In [16]:
print("The dimension of array",b.ndim)

The dimension of array 2


In [18]:
print("The size of array",b.size)

The size of array 12


In [19]:
print("The shape of array",b.shape)

The shape of array (3, 4)


In [24]:
import numpy as np
int8_arr = np.array([1,2,3],dtype = np.int8)
int16_arr = np.array([1000,-2000,3000],dtype=np.int16)
int32_arr = np.array([-100000,200000,300000],dtype=np.int32)
int64_arr = np.array([100000000,200000000],dtype=np.int64)

In [ ]:
#unsigned integers
uint8_arr = np.array([0,233,100],dtype=np.uint8)
uint16_arr = np.array([1000,60000],dtype=np.uint16)

In [ ]:
#float types
float16_arr = np.array([1.1,-2.2,3.3],dtype=np.float16)
float32_arr = np.array([1.123456,2.654321],dtype=np.float32)
float64_arr = np.array([1.23456789,-2.987654321],dtype=np.float64)

In [ ]:
#complex types
complex64_arr = np.array([1+2j,3+4j],dtype=np.complex64)
complex128_arr = np.array([1+2j,3+4j],dtype=np.complex128)

In [28]:
# Boolean type
bool_arr = np.array([True, False, True],dtype=bool)
print("bool:",bool_arr, bool_arr.dtype)
print("-" * 40 )

bool: [ True False  True] bool
----------------------------------------


In [31]:
# string type
string_arr = np.array(["apple", "banana", "cherry"], dtype='U10')

In [30]:
# object type
object_arr = np.array([1, "two", 3.0, True], dtype=object)